"""init saas identity

Revision ID: 2b55acef440b
Revises: 
Create Date: 2026-09-13 20:37:37.090801
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2b55acef440b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_workspace_tenant_id_id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_workspace_tenant_name')
    )
    op.create_index('idx_workspace_storage_path', 'workspaces', ['storage_path'], unique=False)
    op.create_index('idx_workspace_tenant_id', 'workspaces', ['tenant_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('pipeline_type', sa.String(length=100), server_default='cinematic', nullable=False),
    sa.Column('style_playbook', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'workspace_id'], ['workspaces.tenant_id', 'workspaces.id'], name='fk_project_workspace_belongs_to_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'workspace_id', 'slug', name='uq_project_tenant_workspace_slug')
    )
    op.create_index('idx_project_slug', 'projects', ['slug'], unique=False)
    op.create_index('idx_project_status', 'projects', ['status'], unique=False)
    op.create_index('idx_project_tenant_id', 'projects', ['tenant_id'], unique=False)
    op.create_index('idx_project_workspace_id', 'projects', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_project_workspace_id', table_name='projects')
    op.drop_index('idx_project_tenant_id', table_name='projects')
    op.drop_index('idx_project_status', table_name='projects')
    op.drop_index('idx_project_slug', table_name='projects')
    op.drop_table('projects')
    op.drop_index('idx_workspace_tenant_id', table_name='workspaces')
    op.drop_index('idx_workspace_storage_path', table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_table('tenants')
    # ### end Alembic commands ###